import { roomLabel } from './rooms'
import { useEffect, useId, useState, type ReactNode } from 'react'
import { ArrowLeft, ChevronLeft, ChevronRight, FileText, SlidersHorizontal, MoreHorizontal, ImagePlus, Camera, X } from 'lucide-react'
import { Button } from './components/ui/button'
import { Field, FieldLabel, FieldDescription, FieldError, FieldGroup } from './components/ui/field'
import { Input } from './components/ui/input'
import { Textarea } from './components/ui/textarea'
import { Select, SelectTrigger, SelectValue, SelectContent, SelectGroup, SelectItem } from './components/ui/select'
import { Alert, AlertTitle, AlertDescription } from './components/ui/alert'
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from './components/ui/empty'
import { Badge } from './components/ui/badge'
import { Skeleton } from './components/ui/skeleton'
import { Sheet, SheetTrigger, SheetContent, SheetHeader, SheetTitle, SheetDescription, SheetFooter, SheetClose } from './components/ui/sheet'
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem } from './components/ui/dropdown-menu'
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from './components/ui/card'
import { useWorkspace } from './context'
import { dateLabel, statuses, url } from './api'
import type { Event, Photo, Route } from './types'
export function ErrorBox({message}:{message:string}){return message?<Alert variant="destructive"><AlertTitle>Perlu diperiksa</AlertTitle><AlertDescription>{message}</AlertDescription></Alert>:null}
export function Loading(){return <div className="flex flex-col gap-4" aria-label="Memuat" role="status"><Skeleton className="h-10 w-1/3"/><Skeleton className="h-48 w-full"/></div>}
export function Blank({title='Belum ada data',description='Data yang sesuai akan tampil di sini.',children}:{title?:string;description?:string;children?:ReactNode}){return <Empty><EmptyHeader><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader>{children}</Empty>}
export function Heading({title,description,action,back=false}:{title:string;description?:string;action?:ReactNode;back?:boolean}){const w=useWorkspace();return <header className="flex flex-col gap-3"><div className="flex items-center justify-between gap-3 flex-wrap">{back&&<Button variant="ghost" onClick={w.back}><ArrowLeft data-icon="inline-start"/>Kembali</Button>}<div className="ml-auto">{action}</div></div><h1 className="text-2xl font-semibold tracking-tight">{title}</h1>{description&&<p className="text-sm text-muted-foreground">{description}</p>}</header>}
export function Panel({title,description,children}:{title:string;description?:string;children:ReactNode}){return <Card><CardHeader><CardTitle>{title}</CardTitle>{description&&<CardDescription>{description}</CardDescription>}</CardHeader><CardContent>{children}</CardContent></Card>}
export function TextField({label,value,onChange,type='text',error,description,required=false,multiline=false,maxLength,min,max}:{label:string;value:unknown;onChange:(s:string)=>void;type?:string;error?:string;description?:string;required?:boolean;multiline?:boolean;maxLength?:number;min?:string;max?:string}){
 const id=useId();const common={id,value:String(value??''),onChange:(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>onChange(e.target.value),'aria-invalid':!!error,required,maxLength}
 return <Field data-invalid={!!error}><FieldLabel htmlFor={id}>{label}{required?' *':''}</FieldLabel>{multiline?<Textarea {...common} rows={3}/>:<Input {...common} type={type} min={min} max={max} step={type==='number'?'any':undefined}/>} {description&&<FieldDescription>{description}</FieldDescription>}{error&&<FieldError>{error}</FieldError>}</Field>
}
export function Choice({label,value,onChange,items,placeholder='Pilih',disabled=false,error}:{label:string;value:unknown;onChange:(s:string)=>void;items:{value:unknown;label:string}[];placeholder?:string;disabled?:boolean;error?:string}){const id=useId();return <Field data-invalid={!!error} data-disabled={disabled}><FieldLabel htmlFor={id}>{label}</FieldLabel><Select value={String(value??'')||'__empty'} onValueChange={v=>onChange(v==='__empty'?'':v)} disabled={disabled}><SelectTrigger id={id} aria-invalid={!!error} className="w-full"><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent><SelectGroup><SelectItem value="__empty">{placeholder}</SelectItem>{items.filter(x=>String(x.value)!=='').map(x=><SelectItem key={String(x.value)} value={String(x.value)}>{x.label}</SelectItem>)}</SelectGroup></SelectContent></Select>{error&&<FieldError>{error}</FieldError>}</Field>}
export const entries=(o:Record<string,string>)=>Object.entries(o).map(([value,label])=>({value,label}))
export function Status({value}:{value:string}){return <Badge variant={value==='final'||value==='closed'?'secondary':'outline'}>{statuses[value]||value}</Badge>}
export function Pager({page,pages,total,onChange}:{page:number;pages:number;total:number;onChange:(n:number)=>void}){return <div className="flex justify-between items-center gap-3 py-4"><span className="text-sm text-muted-foreground">{total} data · Halaman {page} / {pages}</span><div className="flex gap-2"><Button variant="outline" disabled={page<=1} onClick={()=>onChange(page-1)} aria-label="Halaman sebelumnya"><ChevronLeft/></Button><Button variant="outline" disabled={page>=pages} onClick={()=>onChange(page+1)} aria-label="Halaman berikutnya"><ChevronRight/></Button></div></div>}
export function Pdf({record,room,period}:{record?:unknown;room?:unknown;period?:Route}){const {config}=useWorkspace();const target=room?url(config.inventory,{workspace:'',action:'print_pdf',location_id:room}):url(config.watch,{...period,tab:'pdf',record:record??''});return <Button variant="outline" asChild><a href={target} target="_blank" rel="noopener"><FileText data-icon="inline-start"/>Cetak PDF</a></Button>}
export function Actions({items}:{items:{label:string;run:()=>void;destructive?:boolean}[]}){return <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label="Tindakan lainnya"><MoreHorizontal/></Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuGroup>{items.map(x=><DropdownMenuItem key={x.label} variant={x.destructive?'destructive':'default'} onSelect={x.run}>{x.label}</DropdownMenuItem>)}</DropdownMenuGroup></DropdownMenuContent></DropdownMenu>}
export function Filters({showHistory=false}:{showHistory?:boolean}){const {route,go,options}=useWorkspace();const [values,setValues]=useState(route);return <Sheet onOpenChange={open=>{if(open)setValues(route)}}><SheetTrigger asChild><Button variant="outline"><SlidersHorizontal data-icon="inline-start"/>Filter{(route.room||route.library||route.history==='1')?' •':''}</Button></SheetTrigger><SheetContent><SheetHeader><SheetTitle>Filter daftar</SheetTitle><SheetDescription>Persempit daftar sesuai pekerjaan Anda.</SheetDescription></SheetHeader><FieldGroup className="px-4"><Choice label="Perpustakaan" value={values.library} onChange={v=>setValues({...values,library:v,room:''})} items={options.libraries.map(x=>({value:x.location_id,label:x.location_name}))} placeholder="Semua perpustakaan"/><Choice label="Ruangan" value={values.room} onChange={v=>setValues({...values,room:v})} items={options.rooms.filter(x=>!values.library||x.slims_location_id===values.library).map(x=>({value:x.id,label:roomLabel(x,options.libraries)}))} placeholder="Semua ruangan"/>{showHistory&&<Choice label="Tampilkan" value={values.history||'0'} onChange={v=>setValues({...values,history:v})} items={[{value:'0',label:'Pekerjaan aktif'},{value:'1',label:'Riwayat'}]}/>}</FieldGroup><SheetFooter><SheetClose asChild><Button onClick={()=>go({...route,...values,page:1},true)}>Terapkan filter</Button></SheetClose><SheetClose asChild><Button variant="outline" onClick={()=>go({...route,library:'',room:'',history:'0',page:1},true)}>Reset filter</Button></SheetClose></SheetFooter></SheetContent></Sheet>}
export function Search({placeholder='Cari nama ruangan…'}:{placeholder?:string}){const {route,go}=useWorkspace();const [value,setValue]=useState(String(route.q||''));useEffect(()=>setValue(String(route.q||'')),[route.q]);return <form onSubmit={e=>{e.preventDefault();go({...route,q:value,page:1},true)}} className="flex gap-2 flex-1 max-w-md"><Input aria-label="Cari" value={value} placeholder={placeholder} onChange={e=>setValue(e.target.value)}/><Button variant="outline" type="submit">Cari</Button></form>}
export function History({events}:{events:Event[]}){return <Panel title="Riwayat kegiatan">{!events.length?<Blank description="Belum ada kegiatan tercatat."/>:<ol className="flex flex-col gap-5">{events.map(e=><li key={e.id} className="border-l-2 pl-4"><p className="font-medium">{({import_history:'Riwayat diimpor',import_action:'Pekerjaan historis diimpor',import_verification:'Verifikasi historis dicatat',start:'Pekerjaan dimulai',save_draft:'Draf disimpan',finalize:'Pemeriksaan selesai',save_action:'Pekerjaan disimpan',submit:'Diajukan untuk verifikasi',verify:'Hasil diterima',reject:'Dikembalikan',correction:'Catatan koreksi'} as Record<string,string>)[e.event]||e.event}</p><p className="text-sm text-muted-foreground">{e.actor_name} · {dateLabel(e.created_at)}</p><p className="text-sm whitespace-pre-wrap mt-2">{e.notes}</p></li>)}</ol>}</Panel>}
export function Photos({photos}:{photos:Photo[]}){return <div className="flex flex-wrap gap-3">{photos.map(p=>p.url?<a key={p.id} href={p.url} target="_blank" rel="noopener"><img src={p.url} alt="Foto bukti" loading="lazy" className="h-28 w-36 rounded-lg border object-contain"/></a>:<p key={p.id} className="text-sm text-muted-foreground">Foto lama tidak dapat dibaca.</p>)}</div>}
export function Upload({files,onChange,count=0}:{files:File[];onChange:(f:File[])=>void;count?:number}){const id=useId();const cameraId=useId();const [error,setError]=useState('');const [previews,setPreviews]=useState<string[]>([]);useEffect(()=>{const urls=files.map(f=>URL.createObjectURL(f));setPreviews(urls);return ()=>urls.forEach(u=>URL.revokeObjectURL(u))},[files]);const handle=(picked:File[])=>{if(count+files.length+picked.length>5){setError('Maksimal lima foto.');return}if(picked.some(f=>f.size>2*1024*1024||!['image/jpeg','image/png','image/webp'].includes(f.type))){setError('Gunakan JPEG, PNG, atau WebP maksimal 2 MB.');return}setError('');onChange([...files,...picked])};return <Field><FieldLabel htmlFor={id}><ImagePlus className="size-4"/>Foto bukti</FieldLabel><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" asChild><label htmlFor={cameraId} className="cursor-pointer"><Camera data-icon="inline-start"/>Ambil foto</label></Button><Input id={cameraId} type="file" accept="image/jpeg,image/png,image/webp" capture="environment" className="sr-only" onChange={e=>{const picked=Array.from(e.target.files||[]);e.target.value='';handle(picked)}}/><Button type="button" variant="outline" asChild><label htmlFor={id} className="cursor-pointer"><ImagePlus data-icon="inline-start"/>Pilih dari galeri</label></Button><Input id={id} type="file" multiple accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={e=>{const picked=Array.from(e.target.files||[]);e.target.value='';handle(picked)}}/></div><FieldDescription>Maksimal 5 foto, masing-masing 2 MB.</FieldDescription>{error&&<FieldError>{error}</FieldError>}<div className="flex flex-wrap gap-3">{files.map((f,i)=><div key={i} className="flex flex-col gap-1"><img src={previews[i]} alt={f.name} className="h-24 w-28 object-contain rounded-lg border"/><Button type="button" variant="ghost" onClick={()=>onChange(files.filter((_,n)=>n!==i))}><X data-icon="inline-start"/>Batal</Button></div>)}</div></Field>}
